# Keras NN example

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split

import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
sns.set_style("whitegrid")

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras import regularizers

import sklearn.metrics

Using TensorFlow backend.


In [5]:
import os
%pwd

'C:\\Users\\Peter\\Documents\\code\\nn\\ILearnDeepLearning.py\\01_mysteries_of_neural_networks\\03_numpy_neural_net'

In [6]:
# number of samples in the data set
N_SAMPLES = 10000
# ratio between training and test sets
TEST_SIZE = 0.1
# number of iterations of the model
N_EPOCHS = 50

In [7]:
# boundary of the graph
GRID_X_START = -1.5
GRID_X_END = 1.5
GRID_Y_START = -1.5
GRID_Y_END = 1.5
# output directory (the folder must be created on the drive)
OUTPUT_DIR = "./"

In [65]:
INPUT_DATA=pd.read_csv('y1.csv',index_col=0)

In [66]:
X=INPUT_DATA['X1']

In [67]:
y=INPUT_DATA['Y']

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=42)

In [69]:
totes=print("{:,f}".format(sum(y)))

200,009,923.363842


In [70]:
totes=sum(y)

In [71]:
X_test

6252    6252
4684    4684
1731    1731
4742    4742
4521    4521
6340    6340
576      576
5202    5202
6363    6363
439      439
2750    2750
7487    7487
5272    5272
5653    5653
3999    3999
6033    6033
582      582
9930    9930
7051    7051
8158    8158
9896    9896
2249    2249
4640    4640
9485    9485
4947    4947
9920    9920
1963    1963
8243    8243
6590    6590
8847    8847
        ... 
9615    9615
9217    9217
1672    1672
2358    2358
8467    8467
274      274
2473    2473
5489    5489
4771    4771
2107    2107
7500    7500
4414    4414
8138    8138
8660    8660
8239    8239
2417    2417
8771    8771
2236    2236
3767    3767
9791    9791
9989    9989
9965    9965
7323    7323
1383    1383
3101    3101
3921    3921
6685    6685
3194    3194
1941    1941
7713    7713
Name: X1, Length: 1000, dtype: int64

In [72]:
y_test

6252    25011.087391
4684    18737.523788
1731     6926.783512
4742    18972.062987
4521    18085.885740
6340    25363.716180
576      2306.442401
5202    20810.821740
6363    25455.302315
439      1758.825611
2750    11003.078397
7487    29951.472544
5272    21089.778822
5653    22615.584452
3999    16000.493504
6033    24132.571702
582      2331.472307
9930    39722.852160
7051    28205.708743
8158    32635.191432
9896    39585.412278
2249     9000.841604
4640    18562.683323
9485    37942.968433
4947    19790.455968
9920    39682.200677
1963     7854.799590
8243    32974.798406
6590    26362.322198
8847    35390.316159
            ...     
9615    38462.093878
9217    36871.532923
1672     6691.241149
2358     9433.989385
8467    33873.435441
274      1099.227244
2473     9895.923623
5489    21957.745063
4771    19085.488938
2107     8430.499377
7500    30001.562333
4414    17659.157861
8138    32554.975738
8660    34643.222236
8239    32958.387463
2417     9671.919826
8771    35085

In [73]:
# Building a model
model = Sequential()
model.add(Dense(25, input_dim=1,activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer="sgd", metrics=['accuracy'])
# Training
history = model.fit(X_train, y_train, epochs=200, verbose=0)

In [42]:
# Building a model
model2 = Sequential()
model2.add(Dense(4, input_dim=1,activation='softmax'))
model2.add(Dense(4, activation='softmax'))
model2.add(Dense(1, activation='softmax'))

model2.compile(loss='mean_squared_error', optimizer="sgd", metrics=['mse'])
# Training
history = model2.fit(X_train, y_train, epochs=200, verbose=0)

In [16]:
from sklearn.metrics import mean_squared_error, r2_score

In [75]:
Y_test_hat = model2.predict(X_test)
r2_test = r2_score(y_test, Y_test_hat)
mse= mean_squared_error(y_test, Y_test_hat)
print("r2: {:.2f} - Keras".format(r2_test))

r2: -2.92 - Keras


In [76]:
mse= mean_squared_error(y_test, Y_test_hat)

In [77]:
print("{:,.2f}".format(mse))

536,361,087.41


In [92]:
XR=np.array(X).reshape(-1,1)

In [95]:
XR

array([[   0],
       [   1],
       [   2],
       ...,
       [9997],
       [9998],
       [9999]], dtype=int64)

In [99]:
yR=np.array(y).reshape(-1,1)

In [114]:
y.shape

(10000,)

In [115]:
yR.shape

(10000, 1)

In [116]:
yR

array([[3.77847789e+00],
       [8.71557482e+00],
       [1.22492644e+01],
       ...,
       [3.99920496e+04],
       [3.99946794e+04],
       [3.99998256e+04]])

In [101]:
from sklearn import linear_model

In [102]:
regr = linear_model.LinearRegression().fit(XR,yR)

In [104]:
# The coefficients
print('Coefficients: \n', regr.coef_)

Coefficients: 
 [[3.99999928]]


In [130]:
regr.score(XR,yR)

0.9999999924807546

In [131]:
regr.intercept_

array([2.99592995])